name: Build GKI Kernel 6.1

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc bison flex libssl-dev \
            git wget curl unzip python3 gcc clang llvm lld libncurses5-dev

      - name: Download Toolchain
        run: |
          mkdir -p toolchains
          cd toolchains
          # Clang prebuilt (Android AOSP)
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/master/clang-r450784d.tar.gz -O clang.tar.gz
          tar -xf clang.tar.gz
          # GCC (aarch64)
          wget https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/master.tar.gz -O gcc64.tar.gz
          mkdir gcc64 && tar -xf gcc64.tar.gz -C gcc64

      - name: Build Kernel
        run: |
          export PATH=$GITHUB_WORKSPACE/toolchains/bin:$PATH
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=$GITHUB_WORKSPACE/toolchains/gcc64/bin/aarch64-linux-android-
          export CC=clang
          export LD=ld.lld
          export CLANG_TRIPLE=aarch64-linux-gnu-
          
          make O=out gki_defconfig
          make -j$(nproc) O=out

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: kernel-build
          path: out/arch/arm64/boot/Image.gz
