name: Bazel Kernel Build (Peridot)

on: [workflow_dispatch]

jobs:
  bazel-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Bazel
        run: |
          sudo apt update
          sudo apt install -y bazel

      - name: Run Bazel build
        run: |
          bazel build //:peridot
          bazel build //:peridot_dist  # jika define dist target

      - name: Upload artifacts
        run: |
          cp -r bazel-bin/out/* dist/
        uses: actions/upload-artifact@v4
        with:
          name: peridot-bazel
          path: dist/
