name: Bazel Kernel Build (Peridot)

on:
  workflow_dispatch:

jobs:
  bazel-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Bazelisk (Bazel)
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
          mkdir -p $HOME/bin
          curl -L https://github.com/bazelbuild/bazelisk/releases/download/v1.20.0/bazelisk-linux-amd64 -o $HOME/bin/bazel
          chmod +x $HOME/bin/bazel
          echo "$HOME/bin" >> $GITHUB_PATH
          bazel --version

      - name: Ensure MODULE.bazel exists
        run: |
          if [ ! -f MODULE.bazel ]; then
            echo "MODULE.bazel not found, creating default..."
            echo 'module(name = "kernel_peridot")' > MODULE.bazel
            echo '' >> MODULE.bazel
            echo 'bazel_dep(name = "bazel_skylib", version = "1.4.2")' >> MODULE.bazel
          fi
          cat MODULE.bazel

      - name: List all Bazel targets
        run: |
          echo "=== Available Bazel Targets ==="
          bazel query //... || true

      - name: Try build kernel (Image + modules)
        run: |
          echo "=== Trying to build allmods_peridot ==="
          bazel build //:allmods_peridot || echo "Target allmods_peridot not found"

      - name: Try build kernel dist (boot/dtbo/vendor_boot)
        run: |
          echo "=== Trying to build peridot_dist ==="
          bazel build //:peridot_dist || echo "Target peridot_dist not found"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: peridot-bazel-build
          path: bazel-bin/**
          if-no-files-found: warn
