name: Build Xiaomi Peridot Kernel (Kleaf)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazelbuild/setup-bazel@v5
        with:
          bazel-version: 7.2.1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc bison flex libssl-dev \
            libncurses5-dev libncursesw5-dev git curl zip unzip python3

      - name: Ensure MODULE.bazel exists
        run: |
          if [ ! -f MODULE.bazel ]; then
            echo "module(name = \"kernel_xiaomi_peridot\", version = \"1.0\")" > MODULE.bazel
            echo "bazel_dep(name = \"bazel_skylib\", version = \"1.5.0\")" >> MODULE.bazel
          fi

      - name: Ensure kleaf BUILD.bazel exists
        run: |
          mkdir -p build/kernel/kleaf
          if [ ! -f build/kernel/kleaf/BUILD.bazel ]; then
            echo "# dummy kleaf BUILD file" > build/kernel/kleaf/BUILD.bazel
          fi

      - name: Build kernel
        run: |
          bazel build //:allmods_peridot || bazel build //:peridot_dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-artifacts
          path: >
            ["bazel-bin/**/*.img",
             "bazel-bin/**/*.zip",
             "bazel-bin/**/*.tar.gz",
             "bazel-bin/**/*.bin"]
