name: Kernel Build (Kleaf)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kernel repo
        uses: actions/checkout@v4

      - name: Install Bazel dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip zip python3 python3-pip

      - name: Clone Kleaf + bazel_common_rules
        run: |
          mkdir -p build/kernel
          git clone --depth=1 https://android.googlesource.com/kernel/build build/kernel/build
          ln -sf build/kernel/build/kleaf build/kernel/kleaf
          git clone --depth=1 https://android.googlesource.com/kernel/bazel_common_rules build/bazel_common_rules
          echo 'exports_files(glob(["**/*.bzl"]))' > build/kernel/kleaf/BUILD.bazel
          echo 'exports_files(glob(["**/*.bzl"]))' > build/bazel_common_rules/BUILD.bazel

      - name: Build kernel
        run: |
          bazel build //:peridot
