name: Build Kernel (Kleaf)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kernel repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            bc \
            bison \
            flex \
            git \
            curl \
            zip \
            unzip \
            lz4 \
            zstd \
            libssl-dev \
            openjdk-17-jdk \
            python3 \
            python3-pip

      - name: Setup Bazel (via Bazelisk)
        uses: bazel-contrib/setup-bazel@0.15.0

      - name: Clone Kleaf infra
        run: |
          mkdir -p build/kernel
          git clone --depth=1 https://android.googlesource.com/kernel/build build/kernel/build
          ln -sf build/kernel/build/kleaf build/kernel/kleaf

      - name: Ensure MODULE.bazel exists
        run: |
          if [ ! -f MODULE.bazel ]; then
            cat > MODULE.bazel <<'EOF'
module(
    name = "kernel_xiaomi_peridot",
    version = "1.0",
)
bazel_dep(name = "bazel_skylib", version = "1.4.2")
EOF
          fi

      - name: Build kernel (Kleaf)
        run: |
          set -e
          echo ">>> Trying peridot_dist target..."
          if ! bazel build //:peridot_dist --verbose_failures; then
            echo ">>> peridot_dist failed, trying allmods_peridot..."
            bazel build //:allmods_peridot --verbose_failures
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-artifacts
          path: |
            bazel-bin/**/*.img
            bazel-bin/**/*.zip
            bazel-bin/**/*.tar.gz
