name: Build Kernel (Kleaf)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            bc \
            bison \
            flex \
            git \
            curl \
            zip \
            unzip \
            lz4 \
            zstd \
            libssl-dev \
            openjdk-17-jdk \
            python3 \
            python3-pip

      - name: Install Bazelisk
        run: |
          sudo curl -L "https://github.com/bazelbuild/bazelisk/releases/download/v1.22.0/bazelisk-linux-amd64" -o /usr/local/bin/bazel
          sudo chmod +x /usr/local/bin/bazel
          bazel version

      - name: Ensure MODULE.bazel exists
        run: |
          if [ ! -f MODULE.bazel ]; then
            cat > MODULE.bazel <<'EOF'
module(
    name = "kernel_xiaomi_peridot",
    version = "1.0",
    repo_name = "kernel_xiaomi_peridot",
)

bazel_dep(name = "bazel_skylib", version = "1.4.2")
bazel_dep(name = "rules_cc", version = "0.0.8")
EOF
          fi

      - name: Build kernel (peridot_dist)
        run: |
          bazel build //:peridot_dist --verbose_failures || \
          bazel build //:allmods_peridot --verbose_failures

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-artifacts
          path: |
            bazel-bin/**/*.img
            bazel-bin/**/*.zip
            bazel-bin/**/*.tar.gz
            bazel-bin/**/*.bin
