name: Kernel Build (Kleaf)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Bazelisk (Bazel wrapper)
        run: |
          mkdir -p $HOME/bin
          curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -o $HOME/bin/bazel
          chmod +x $HOME/bin/bazel
          echo "$HOME/bin" >> $GITHUB_PATH
          bazel version

      - name: Clone Bazel common rules
        run: |
          rm -rf build/bazel_common_rules
          git clone --depth=1 https://android.googlesource.com/kernel/bazel/common_rules build/bazel_common_rules

      - name: Clone Kleaf
        run: |
          rm -rf build/kernel
          mkdir -p build/kernel
          git clone --depth=1 https://android.googlesource.com/kernel/build build/kernel/build
          ln -sf build/kernel/build/kleaf build/kernel/kleaf
          mkdir -p build/kernel/kleaf
          echo 'package(default_visibility = ["//visibility:public"])' > build/kernel/kleaf/BUILD.bazel
          echo 'exports_files(glob(["**/*.bzl"]))' >> build/kernel/kleaf/BUILD.bazel

      - name: Build kernel
        run: |
          bazel build //:kernel_xiaomi_peridot_dist --verbose_failures

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: bazel-bin/**/*.img
