name: Build Kernel with Kleaf

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bazelisk
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip zip python3
          curl -L https://github.com/bazelbuild/bazelisk/releases/download/v1.20.0/bazelisk-linux-amd64 -o /usr/local/bin/bazel
          chmod +x /usr/local/bin/bazel
          bazel version

      - name: Clone Kleaf
        run: |
          mkdir -p build/kernel
          git clone --depth=1 https://android.googlesource.com/kernel/build build/kernel/build
          ln -sf build/kernel/build/kleaf build/kernel/kleaf
          mkdir -p build/kernel/build/kleaf
          cat > build/kernel/build/kleaf/BUILD.bazel <<'EOF'
package(default_visibility = ["//visibility:public"])

exports_files([
    "kernel.bzl",
])

exports_files(glob(["**/*.bzl"]))
EOF

      - name: Build kernel
        run: |
          bazel build //:kernel_xiaomi_peridot_dist --verbose_failures

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: bazel-bin/*
