name: Kernel Build (msm.peridot)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc bison flex libssl-dev \
            libncurses5-dev libncursesw5-dev gcc clang lld python3 wget git

      - name: Clone kernel build tools
        run: |
          mkdir -p build/kernel
          git clone --depth=1 https://android.googlesource.com/kernel/build build/kernel/build

      - name: Start kernel build (msm.peridot)
        run: |
          export BUILD_CONFIG=build.config.msm.peridot
          bash build/kernel/build/build.sh

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-msm-peridot
          path: out/**/*.img
