name: Build Kernel Peridot Full

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang lld gcc-aarch64-linux-gnu \
            bison flex libncurses5-dev libssl-dev git curl \
            python3 python3-pip unzip

      - name: Install Bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.23.0/bazelisk-linux-amd64"
          chmod +x bazelisk-linux-amd64
          sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel
          bazel version

      - name: Ensure MODULE.bazel exists
        run: |
          if [ ! -f MODULE.bazel ]; then
            echo 'module(name = "kernel_xiaomi_peridot", version = "1.0")' > MODULE.bazel
          fi

      - name: Clone required subrepos
        run: |
          mkdir -p build/kernel
          git clone --depth=1 https://android.googlesource.com/kernel/build build/kernel/build
          if [ ! -d build/bazel_common_rules ]; then
            git clone --depth=1 https://android.googlesource.com/kernel/bazel_common_rules build/bazel_common_rules
          fi

      - name: Create BUILD.bazel for kleaf
        run: |
          mkdir -p build/kernel/build/kleaf
          echo 'exports_files(glob(["**/*.bzl"]))' > build/kernel/build/kleaf/BUILD.bazel

      - name: Run Python Bazel build
        run: |
          python3 -u build.with.bazel.py

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-artifacts
          path: out/**/*.img
