name: Build Kernel (Kleaf)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget curl unzip python3 python3-pip build-essential gcc g++ make \
            openjdk-11-jdk pkg-config zip zlib1g-dev

      - name: Install Bazelisk (Bazel wrapper)
        run: |
          sudo curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 \
            -o /usr/local/bin/bazel
          sudo chmod +x /usr/local/bin/bazel
          bazel version

      - name: Clone Kleaf
        run: |
          mkdir -p build/kernel
          git clone --depth=1 https://android.googlesource.com/kernel/build build/kernel/build
          ln -sf build/kernel/build/kleaf build/kernel/kleaf
          # Buat BUILD.bazel kalau belum ada
          if [ ! -f build/kernel/kleaf/BUILD.bazel ]; then
            echo 'exports_files(glob(["**/*.bzl"]))' > build/kernel/kleaf/BUILD.bazel
          fi

      - name: Build kernel
        run: |
          bazel build //:kernel

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: boot-image
          path: bazel-bin/**/*.img
