name: Build Kernel 6.1 Peridot

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ARCH: arm64
      CROSS_COMPILE: aarch64-linux-gnu-

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang lld gcc-aarch64-linux-gnu \
            bc bison flex libncurses5-dev libssl-dev \
            u-boot-tools device-tree-compiler git curl python3 python3-pip unzip

      - name: Setup output directory
        run: mkdir -p out

      - name: Build kernel
        run: |
          cd kernel
          make peridot_defconfig
          make -j$(nproc)
          # Copy generated Image and dtb to out
          cp arch/arm64/boot/Image.gz-dtb ../out/
          if [ -f arch/arm64/boot/dtbo.img ]; then
            cp arch/arm64/boot/dtbo.img ../out/
          fi
          # Optionally pack boot.img (requires mkbootimg)
          if command -v mkbootimg >/dev/null 2>&1; then
            mkbootimg --kernel arch/arm64/boot/Image.gz-dtb \
                      --ramdisk ramdisk.img \
                      --output ../out/boot.img || true
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-artifacts
          path: out/
